run:
  timeout: 5m

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - fmt
          - os
          - io
          - time
          - bytes
          - strings
          - context
          - net/http
          - net/url
          - mime/multipart
          - encoding/json
          - github.com/pkg/errors
          - github.com/aejoy/go-pkg
          - github.com/aejoy/prisma-sdk-go
  lll:
    line-length: 200

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - funlen
    - gochecknoglobals
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - err113
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl